### ISSUE TITLE
音声合成API提供終了による使用不可能化

### ISSUE THREAD

**Issue by NSRHT** [dayaman/dsc_readup#126]
5月16日にドコモより「音声合成【Powered by AI】API提供終了のお知らせ」が来ました。
よってこのBOTは6月17日に使用不可能になります。
音声の生成方法を変更し延命をする予定はありますか？

**Comment by dayaman** [comment]
エーアイの音声合成エンジンを利用したTTS Botであることが喋太郎の特徴と考えています。サービスを続行させるための検討は行なっております。しかし、別の音声合成システムを利用してのサービス続行は行いません。
