### ISSUE TITLE
他のBotの発言を読み上げない

### ISSUE THREAD

**Issue by Autumn60** [dayaman/dsc_readup#35]
突然のIssue失礼します。
喋太郎が他のBotの発言を読み上げないのは仕様でしょうか？

**Comment by dayaman** [comment]
その仕様にしております。
喋太郎自身の発言を読み上げないようにするために、そもそもBotを弾く設定ですね。
他のBotは読み上げるように対応いたします。

**Comment by dayaman** [comment]
Botの読み上げモードを検討

**Comment by dayaman** [comment]
検討した結果、他のBotもろとも読み上げない仕様とします。申し訳ありませんが、一般ユーザのみ読み上げることとなります。
