### ISSUE TITLE
一定時間、読み上げがない場合に自動でボイチャから退出させたい

### ISSUE THREAD

**Issue by nagaoka252510** [dayaman/dsc_readup#66]
主に寝落ちなどで利用者がいなくなってもボイチャに喋太郎が残り続ける
デフォルトで60分間、読み上げがない場合に自動でボイスチャンネルから退出させたい

**Comment by dayaman** [comment]
時間のカウンターはどうやって置きましょうかね...。今の喋太郎はイベント駆動？なんで常時稼働するtimeカウンターをどうやって実装するか。
threading?

**Comment by nagaoka252510** [comment]
見方を変えて、ボイスチャンネル参加者が喋太郎のみになったとき
(ユーザのボイスチャンネル退出イベントをトリガにして)
ボイスチャンネルから喋太郎自身も退出するという案はどうだろう

他にも案がないかAPIドキュメント漁ります

**Comment by dayaman** [comment]
https://discordpy.readthedocs.io/ja/latest/api.html#discord.on_voice_state_update
これそれっぽい

**Comment by dayaman** [comment]
ボイスチャンネルのステータスが何かしら変わるたびにイベントが発生するみたいですね。発生元ボイスチャンネルを取得できるようなので、そのたびにメンバーを取得して0人なら切断(or Botのみなら切断)

**Comment by dayaman** [comment]
あ、勢いでガーーーーっと実装しちゃったんですけど、 @nagaoka252510 さん書く予定でしたか...?

**Comment by nagaoka252510** [comment]
早い方が正義なんで大丈夫ですよ
お疲れ様です！

**Comment by dayaman** [comment]
おつありです！では、クローズします
