### ISSUE TITLE
パパが認知してくれない

### ISSUE THREAD

**Issue by karinto3375** [dayaman/dsc_readup#93]
ﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟﾊﾟっw

**Comment by dayaman** [comment]
うるせえ黙れ。
